# This file was generated by GoReleaser. DO NOT EDIT.
class Nyan < Formula
  desc "Colored cat command which supports syntax highlighting."
  homepage "https://github.com/toshimaru/nyan"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/toshimaru/nyan/releases/download/v0.1.0/nyan_Darwin_x86_64.tar.gz"
    sha256 "e1de1a1a666d21ec095fb558474d78f2751ce7677837a43b2b438d78396c218f"
  elsif OS.linux?
    url "https://github.com/toshimaru/nyan/releases/download/v0.1.0/nyan_Linux_x86_64.tar.gz"
    sha256 "2ecafa952397b61f978eb85453143aadbd85bd56baa4924c96f09df473f6f54f"
  end

  def install
    bin.install "nyan"
  end

  test do
    system "#{bin}/nyan -v"
  end
end
