# This file was generated by GoReleaser. DO NOT EDIT.
class Nyan < Formula
  desc "Colored cat command which supports syntax highlighting."
  homepage "https://github.com/toshimaru/nyan"
  version "0.3.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/toshimaru/nyan/releases/download/v0.3.1/nyan_Darwin_x86_64.tar.gz"
    sha256 "05dafb186d8f31141a8bddbfe13909bf371faa249b27251d084dbe63d430c886"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/toshimaru/nyan/releases/download/v0.3.1/nyan_Linux_x86_64.tar.gz"
      sha256 "0494d5ed9f1d954cc7c955492ad60700e6eb30050aded5493bc13ca66785c94d"
    end
  end

  def install
    bin.install "nyan"
  end

  test do
    system "#{bin}/nyan -v"
  end
end
